import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const initialValues = {
	name: "",
	usd: 0,
	usd_24h_change: 0,
};

export default function Home() {
	const [coins, setCoins] = useState([initialValues]);

	useEffect(() => {
		fetch(
			"https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Ctether%2Cethereum%2Clitecoin%2Ccardano%2Cdogecoin&vs_currencies=usd&include_24hr_change=true",
		)
			.then((res) => res.json())
			.then((json) => {
				const names = Object.getOwnPropertyNames(json);
				let aux = [];

				for (let name of names) {
					aux.push({ name, ...json[name] });
				}

				setCoins(aux);
			});
	}, []);

	return (
		<>
			<Head>
				<title>Crypto Price App | by Joldev</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<main className="flex flex-col items-center">
				<div className="py-20">
					<h1 className="text-center text-white font-bold mb-5 text-[36px]">
						Crypto Price App
					</h1>
					{coins.map((coin) => {
						return (
							<div
								className={`flex m-5 w-[460px] h-4/5 rounded ${
									coin.usd_24h_change < 0
										? "bg-gradient-to-r from-[#202022] to-[#aa444425] text-[#ff4040]"
										: "bg-gradient-to-r from-[#202022] to-[#4eb64510] text-[#30ff20]"
								}`}
								key={coin.name}
							>
								<div className="w-[80px] h-full grid place-items-center">
									<img
										className="h-[70%]"
										src={`images/${coin.name}.png`}
										alt=""
									/>
								</div>
								<div className="h-full flex flex-col justify-start">
									<h3 className="text-white text-[26px] uppercase">
										{coin.name}
									</h3>
									<span className="text-[#aaa] text-[14px] font-medium">
										/USD
									</span>
								</div>
								<div className="grid items-center ml-auto pt-[8px] pr-[22px] text-right">
									<span className="text-[26px] font-bold mt-[-6px]">
										${coin.usd}
									</span>
									<span className="text-[#aaa] text-base font-semibold mt-[-30px]">
										${coin.usd_24h_change.toFixed(5)}
									</span>
								</div>
							</div>
						);
					})}
				</div>
			</main>
		</>
	);
}
